### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Jinjiang** [weexteam/vue-framework-for-Apache-Weex#9]
Milestone 1
- [x] 补全测试 (Write test for Weex platform) #10
- [x] 仓库合并 (Merge this repo into vue main repo and re-fork it here)
  - [x] 合并已有的提交 (Merge all commits here)
  - [x] Weex JS Framework 打包脚本 (Write build script for Weex)

Milestone 2
- [x] streaming render #2
- [x] Vue 适配：双向绑定 (Support two-way binding)
  - [x] 支持 `v-model` (Support `v-model`) #3
  - ~~支持 `.sync` (Support `.sync`)~~
- [x] Vue 适配：transition 支持 (Support `<transition>`) #1 [wip]
- [x] 集中关注内存管理和页面间串扰问题 (Focus on memory management & inter-page crosstalk issues)
- [x] Vue 在 web 和 weex 可用特性范围和开发方式的差异整理 (Sort differences between using Vue in Web and Weex) #11 #14 #15 
- [x] 从 `*.we` 过渡到 `*.vue` 的开发体验整理 (List transition from `*.we` to `*.vue` development experience) #4 #13 
  - [x] `*.we` -> `*.vue` 转换工具 (Conversion tool from `*.we` to `*.vue` ) [npm package](https://www.npmjs.com/package/weex-vue-migration)

Milestone 3
- [x] 重构 Vue 2.0 版的 Weex HTML5 Render (Rebuild Weex HTML5 Render using Vue 2.0) [repo](https://github.com/Hanks10100/weex/tree/html5-feature-vue-render/html5/render/vue)
- [x] 尝试完成 HackerNews (Try build a HackerNews app) [repo](https://github.com/weexteam/weex-hackernews)
  - [x] Vuex 适配 (Adapt vuex)
  - [x] Vue-router 适配 (Adapt vue-router)
  - [x] Vue-cli 模板 (Vue-cli template)
- [x] weex-loader
  - [x] weex-vue-loader
- [ ] Documentation

Milestone 4

- [x] adapt weex-devtool
- [x] adapt weex-toolkit
- [x] adapt weex-pack

Milestone 5

- [ ] 服务端渲染 / 预编译方案 (server-side rendering / pre-compile)
- [ ] Weex DevTools 支持 Vue 2.0 插件 (Weex DevTools support vue-devtools extension)
- [ ] weex-vue-loader hot-reload
- [ ] vue-cli template for weex-pack
- [ ] `<transition-group>`
- [ ] supporting TypeScript

Further
- 发展通用组件 (Support "universal" Vue components)
  - Weex 支持所有HTML标签 (Support almost HTML tags in Weex)
  - Weex 明确列出支持的CSS样式范围 (List supported CSS range)
  - Weex 公布 JS APIs 支持情况和未来的 Roadmap (List all supported JS APIs from native and the roadmap in the future)
- Weex playground website 支持 Vue (Weex playground website support `*.vue`)
- 实例收集 (Examples collection)
- 社区和生态建设 (Build community and eco system together)

**Comment by littleseven** [comment]
Weex 支持所有HTML标签 ？Further 是要做一个瘦身版浏览器？

**Comment by Jinjiang** [comment]
@littleseven 浏览器这个话题太大了，但是可以正常渲染 p, h1~h6, ul, ol 这类的 HTML 标签是有机会的，未来会逐步细化讨论

**Comment by kramer65** [comment]
This is awesome! I can't wait to build native apps using vuejs!

**Comment by transtone** [comment]
任重道远啊，加油！

**Comment by Solinx** [comment]
This is great! I'm not liking the react native syntax much.

**Comment by dewdad** [comment]
Yeah! Way to go people! This is what I call progress.

**Comment by hustcer** [comment]
想知道 Milestone 3 完成大概在什么时间点？可以毛估估。

**Comment by Hanks10100** [comment]
Here is a task list (github porjects): https://github.com/weexteam/weex-vue-framework/projects/1?fullscreen=true

**Comment by hf20** [comment]
想知道 Milestone 3 完成大概在什么时间点？

**Comment by linkdesu** [comment]
真没想到 vue 也会发展出这条路！:100: 强力前排支持，虽然不太了解实现跨平台这方面，但是我会试着在 vue 本身以及组件库、编辑器插件方面做一些贡献 :sparkles: ~~

**Comment by Jinjiang** [comment]
@hf20 年底

**Comment by acathur** [comment]
@Jinjiang 16年年底？

**Comment by Char-Ten** [comment]
@linkdesu vue大法好！

**Comment by tiye** [comment]
Coming from this [reply](https://medium.com/@youyuxi/pretty-good-comparison-overall-but-a-few-points-id-like-to-discuss-e4f6460e75d5#.zhfdvku3h). Personally I don't think this Roadmap is clear enough to follow. Which feature at which version in which month, I can't see them in this list. Those information can be important when I make plans doing things with Weex.

**Comment by hustcer** [comment]
Waiting for the documents of `Milestone 3`.

**Comment by 7ammer** [comment]
^^^Documentation for milestone 3 would be awesome! Can't wait to learn about all the new additions. Do we have a rough date of release on it?

**Comment by kramer65** [comment]
I'm also very curious about the "_list all supported JS APIs from native and the roadmap in the future_" as is written under "_Further_".. :-)

Anyway, I'm checking this issue every couple days to see how progress is going, and I like the speed you guys have. Keep up the good work!

**Comment by tonyyls** [comment]
it will be perfect if Weex support local image.

**Comment by higchiu** [comment]
Weex HTML5 Render 的编写是给 server-side rendering 埋坑啊，这么多window什么的

**Comment by kramer65** [comment]
Is anything still happening here? It would be great if this becomes reality!

**Comment by benmccallum** [comment]
+1 is anything still happening? Last commit was 8 months ago?!

**Comment by james-andrewsmith** [comment]
@kramer65 @benmccallum 

It became an apache incubator project the github mirrored repository is here https://github.com/apache/incubator-weex/branches
